In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

df = pd.DataFrame({'Fruits':['Apple','Banana','Banana','Mongo','Banana']})
label_enc = LabelEncoder()
num_type = label_enc.fit_transform(df['Fruits'])
print(num_type)
onehot_enc = OneHotEncoder()
num_type_onehot = onehot_enc.fit_transform(num_type.reshape(-1,1))
print(num_type_onehot.toarray())

/Users/yaohanjiang/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


[0 1 1 2 1]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


/Users/yaohanjiang/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/yaohanjiang/opt/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [8]:
pd.get_dummies(df)

Fruits_Apple  Fruits_Banana  Fruits_Mongo
0             1              0             0
1             0              1             0
2             0              1             0
3             0              0             1
4             0              1             0

In [ ]:
from sklearn.compose import ColumnTransformer 
ct = ColumnTransformer([("Name_Of_Your_Step", OneHotEncoder(),[0])], remainder="passthrough")) 
# The last arg ([0]) is the list of columns you want to transform in this step
ct.fit_transform(X) 

In [50]:
df1

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [45]:
df1 = pd.read_csv('http://bit.ly/kaggletrain')


In [49]:
df1.shape

(891, 12)

In [48]:
df1.loc[df1.Embarked.notna(), ['Survived', 'Pclass', 'Sex', 'Embarked']]

Survived  Pclass     Sex Embarked
0           0       3    male        S
1           1       1  female        C
2           1       3  female        S
3           1       1  female        S
4           0       3    male        S
..        ...     ...     ...      ...
886         0       2    male        S
887         1       1  female        S
888         0       3  female        S
889         1       1    male        C
890         0       3    male        Q

[889 rows x 4 columns]

In [9]:
df1 = pd.DataFrame({'Fruits':['Apple','Banana','Banana','Mongo','Banana'], 'number':[5, None, 3,None,1]})


In [11]:
# how many missing values for each Column
df1.isnull().sum()

Fruits    0
number    2
dtype: int64

In [12]:
# how many missing values for each Row
df1.isnull().sum(axis =1)

0    0
1    1
2    0
3    1
4    0
dtype: int64

In [13]:
# drop na (drop any rows with na)
df1.dropna()

# drop columns with any na
df1.dropna(axis = 1)

Fruits  number
0   Apple     5.0
2  Banana     3.0
4  Banana     1.0

In [14]:
df1.dropna(how = 'all')

Fruits  number
0   Apple     5.0
1  Banana     NaN
2  Banana     3.0
3   Mongo     NaN
4  Banana     1.0

In [19]:
df1.dropna(how = 'all')
# Require that many non-NA values
df1.dropna(thresh=3)
df1.dropna(subset = ['Fruits'])

Empty DataFrame
Columns: [Fruits, number]
Index: []

In [23]:
from sklearn.preprocessing import Imputer
import numpy as np

arr = np.array([[1,2,3,4],[2,None,5,None],[2,3,4,None]])
# mean from same column 
imputer = Imputer(strategy ='mean')
imputer.fit_transform(arr) 

/Users/yaohanjiang/opt/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


array([[1. , 2. , 3. , 4. ],
       [2. , 2.5, 5. , 4. ],
       [2. , 3. , 4. , 4. ]])

In [29]:
from sklearn.impute.MICEImputer

SyntaxError: invalid syntax (<ipython-input-29-416c871466cc>, line 1)

In [40]:
from sklearn.preprocessing import StandardScaler

scale = StandardScaler()
arr = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]],dtype =float)
scale.fit(arr)

print(scale.mean_)
print(scale.scale_)
print(scale.transform(arr))

# feed new data for the same scaler 
scale.transform([[4,4,4,4]])


[2. 2. 2. 2.]
[0.81649658 0.81649658 0.81649658 0.81649658]
[[-1.22474487 -1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487  1.22474487]]


array([[2.44948974, 2.44948974, 2.44948974, 2.44948974]])

In [53]:
from sklearn.preprocessing import MinMaxScaler
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler()
scaler.fit(data)
print(scaler.data_max_)
print(scaler.data_min_)
print(scaler.scale_)

print(scaler.transform(data))



[ 1. 18.]
[-1.  2.]
[0.5    0.0625]
[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]


In [54]:
from sklearn.preprocessing import MaxAbsScaler
X = [[ 1., -1.,  2.],
     [ 2.,  0.,  0.],
    [ 0.,  1., -1.]]

transformer = MaxAbsScaler().fit(X)
transformer.transform(X)

array([[ 0.5, -1. ,  1. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  1. , -0.5]])

In [29]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
df = pd.DataFrame({'a':np.random.rand(5),'b':np.random.rand(5)})
cube = PolynomialFeatures(degree=2)
cube_features = cube.fit_transform(df)
cols = cube.get_feature_names()
pd.DataFrame(cube_features,columns=cols)

1        x0        x1      x0^2     x0 x1      x1^2
0  1.0  0.737737  0.778589  0.544255  0.574393  0.606200
1  1.0  0.514332  0.649603  0.264537  0.334111  0.421984
2  1.0  0.550124  0.603712  0.302636  0.332116  0.364468
3  1.0  0.260384  0.335987  0.067800  0.087486  0.112888
4  1.0  0.211664  0.154232  0.044802  0.032645  0.023788

1        x0        x1      x0^2     x0 x1      x1^2
0  1.0  0.813839  0.899997  0.662334  0.732453  0.809995
1  1.0  0.402982  0.532934  0.162395  0.214763  0.284018
2  1.0  0.405475  0.162143  0.164410  0.065745  0.026290
3  1.0  0.404204  0.748002  0.163381  0.302346  0.559508
4  1.0  0.160130  0.390722  0.025642  0.062566  0.152663

a         b
0  0.813839  0.899997
1  0.402982  0.532934
2  0.405475  0.162143
3  0.404204  0.748002
4  0.160130  0.390722